steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "build-compass-admin"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REGISTRY}/compass\
        -admin:${SHORT_SHA}"
      - "--cache-from"
      - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REGISTRY}/compass\
        -admin:latest"
      - "--build-arg"
      - "BUILDKIT_INLINE_CACHE=1"
      - "--build-arg"
      - "APP_TYPE=admin"
      - "--build-arg"
      - "PORT=3027"
      - "--build-arg"
      - "NODE_VERSION=20"
      - "--build-arg"
      - "ALPINE_VERSION=3.19"
      - "-f"
      - "docker/Dockerfile"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    id: "build-compass-driver"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REGISTRY}/compass\
        -driver:${SHORT_SHA}"
      - "--cache-from"
      - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REGISTRY}/compass\
        -driver:latest"
      - "--build-arg"
      - "BUILDKIT_INLINE_CACHE=1"
      - "--build-arg"
      - "APP_TYPE=driver-mobile"
      - "--build-arg"
      - "PORT=3028"
      - "--build-arg"
      - "NODE_VERSION=20"
      - "--build-arg"
      - "ALPINE_VERSION=3.19"
      - "-f"
      - "docker/Dockerfile"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    id: "build-compass-terminal"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REGISTRY}/compass\
        -terminal:${SHORT_SHA}"
      - "--cache-from"
      - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REGISTRY}/compass\
        -terminal:latest"
      - "--build-arg"
      - "BUILDKIT_INLINE_CACHE=1"
      - "--build-arg"
      - "APP_TYPE=terminal"
      - "--build-arg"
      - "PORT=3029"
      - "--build-arg"
      - "NODE_VERSION=20"
      - "--build-arg"
      - "ALPINE_VERSION=3.19"
      - "-f"
      - "docker/Dockerfile"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    id: "push-compass-admin"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REGISTRY}/compass\
        -admin:${SHORT_SHA}"
    waitFor: [ "build-compass-admin" ]

  - name: "gcr.io/cloud-builders/docker"
    id: "push-compass-driver"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REGISTRY}/compass\
        -driver:${SHORT_SHA}"
    waitFor: [ "build-compass-driver" ]

  - name: "gcr.io/cloud-builders/docker"
    id: "push-compass-terminal"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REGISTRY}/compass\
        -terminal:${SHORT_SHA}"
    waitFor: [ "build-compass-terminal" ]

timeout: 1800s

options:
  machineType: "N1_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: "ALLOW_LOOSE"

substitutions:
  _REGION: "europe-west4"
  _PROJECT_ID: "compass-transfer-prod"
  _ARTIFACT_REGISTRY: "compass-images"

images:
  - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REGISTRY}/compass-adm\
    in:${SHORT_SHA}"
  - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REGISTRY}/compass-dri\
    ver:${SHORT_SHA}"
  - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_ARTIFACT_REGISTRY}/compass-ter\
    minal:${SHORT_SHA}"
